"""init tables

Revision ID: 42982028ec09
Revises: 
Create Date: 2026-08-15 07:28:37.798677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# 自定义金额类型（Money TypeDecorator）需要显式导入，autogenerate 不会自动加
import invoicing.models.fields

# revision identifiers, used by Alembic.
revision: str = '42982028ec09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailboxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('imap_host', sa.String(length=256), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('use_ssl', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('password_encrypted', sa.String(length=512), nullable=False),
    sa.Column('folder', sa.String(length=128), nullable=False),
    sa.Column('keywords', sa.String(length=256), nullable=False),
    sa.Column('poll_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(length=256), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(length=256), nullable=True),
    sa.Column('smtp_password_encrypted', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_uid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mailbox_id', sa.Integer(), nullable=True),
    sa.Column('email_message_id', sa.String(length=512), nullable=True),
    sa.Column('email_subject', sa.String(length=512), nullable=True),
    sa.Column('invoice_code', sa.String(length=32), nullable=True),
    sa.Column('invoice_number', sa.String(length=32), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('amount_without_tax', invoicing.models.fields.Money(precision=14, scale=2), nullable=True),
    sa.Column('tax_amount', invoicing.models.fields.Money(precision=14, scale=2), nullable=True),
    sa.Column('total_amount', invoicing.models.fields.Money(precision=14, scale=2), nullable=True),
    sa.Column('total_amount_cn', sa.String(length=128), nullable=True),
    sa.Column('seller_name', sa.String(length=256), nullable=True),
    sa.Column('seller_tax_id', sa.String(length=64), nullable=True),
    sa.Column('buyer_name', sa.String(length=256), nullable=True),
    sa.Column('buyer_tax_id', sa.String(length=64), nullable=True),
    sa.Column('invoice_type', sa.String(length=32), nullable=True),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=8), nullable=False),
    sa.Column('xml_url', sa.String(length=512), nullable=True),
    sa.Column('parse_source', sa.String(length=32), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('verify_status', sa.String(length=16), nullable=False),
    sa.Column('verify_detail', sa.JSON(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duplicate_flag', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('review_note', sa.String(length=1024), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_created_at', 'invoices', ['created_at'], unique=False)
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.create_index('uq_invoices_email_message_id', 'invoices', ['email_message_id'], unique=True, postgresql_where=sa.text('email_message_id IS NOT NULL'), sqlite_where=sa.text('email_message_id IS NOT NULL'))
    # 手工补充：SQLite 无法反射表达式索引，autogenerate 跳过了 uq_invoices_dedup_key
    op.create_index(
        'uq_invoices_dedup_key',
        'invoices',
        ['tenant_id', sa.text("coalesce(invoice_code, '')"), 'invoice_number'],
        unique=True,
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    op.drop_index('uq_invoices_dedup_key', table_name='invoices')
    op.drop_index('uq_invoices_email_message_id', table_name='invoices', postgresql_where=sa.text('email_message_id IS NOT NULL'), sqlite_where=sa.text('email_message_id IS NOT NULL'))
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.drop_index('ix_invoices_created_at', table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('users')
    op.drop_table('mailboxes')
    # ### end Alembic commands ###
