"""invoices 红字发票标记

Revision ID: 4f83effb6e40
Revises: eb3955ce0f84
Create Date: 2026-08-18 12:04:13.215237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f83effb6e40'
down_revision: Union[str, Sequence[str], None] = 'eb3955ce0f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('red_flag', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'red_flag')
    # ### end Alembic commands ###
