"""bank_receipts 银行回单

Revision ID: d707b8009db1
Revises: 4f83effb6e40
Create Date: 2026-08-18 13:55:07.324302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# 自定义金额类型（Money TypeDecorator）需要显式导入，autogenerate 不会自动加
import invoicing.models.fields  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'd707b8009db1'
down_revision: Union[str, Sequence[str], None] = '4f83effb6e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=8), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('counterparty_name', sa.String(length=256), nullable=True),
    sa.Column('amount', invoicing.models.fields.Money(precision=14, scale=2), nullable=True),
    sa.Column('abstract', sa.String(length=256), nullable=True),
    sa.Column('paired_invoice_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paired_invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_receipts')
    # ### end Alembic commands ###
