"""invoices 数字员工字段（费用归类+AI 预判）

Revision ID: eb3955ce0f84
Revises: bdc40a40c6bf
Create Date: 2026-08-17 22:06:45.694342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3955ce0f84'
down_revision: Union[str, Sequence[str], None] = 'bdc40a40c6bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('expense_type', sa.String(length=32), nullable=True))
    op.add_column('invoices', sa.Column('cost_center', sa.String(length=128), nullable=True))
    op.add_column('invoices', sa.Column('description', sa.String(length=256), nullable=True))
    op.add_column('invoices', sa.Column('submitted_by_user_id', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('ai_review_verdict', sa.String(length=16), nullable=True))
    op.add_column('invoices', sa.Column('ai_review_reason', sa.String(length=512), nullable=True))
    op.add_column('invoices', sa.Column('ai_review_confidence', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('ai_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'ai_reviewed_at')
    op.drop_column('invoices', 'ai_review_confidence')
    op.drop_column('invoices', 'ai_review_reason')
    op.drop_column('invoices', 'ai_review_verdict')
    op.drop_column('invoices', 'submitted_by_user_id')
    op.drop_column('invoices', 'description')
    op.drop_column('invoices', 'cost_center')
    op.drop_column('invoices', 'expense_type')
    # ### end Alembic commands ###
